export const ADD_ITEM_TO_CART_REQUEST = "ADD_ITEM_TO_CART_REQUEST"
export const ADD_ITEM_TO_CART_SUCCESS = "ADD_ITEM_TO_CART_SUCCESS"
export const ADD_ITEM_TO_CART_FAILUER = "ADD_ITEM_TO_CART_FAILUER"

export const GET_CART_ITEM_REQUEST = "GET_CART_ITEM_REQUEST"
export const GET_CART__ITEM_SUCCESS = "GET_CART__ITEM_SUCCESS"
export const GET_CART_ITEM_FAILUER = "GET_CART_ITEM_FAILUER"

export const REMOVE_CART_ITEM_REQUEST = "REMOVE_CART_ITEM_REQUEST"
export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS"
export const REMOVE_CART_ITEM_FAILUER = "REMOVE_CART_ITEM_FAILUER"

export const UPDATE_CART_ITEM_REQUEST = "UPDATE_CART_ITEM_REQUEST"
export const UPDATE_CART_ITEM_SUCCESS = "UPDATE_CART_ITEM_SUCCESS"
export const UPDATE_CART_ITEM_FAILUER = "UPDATE_CART_ITEM_FAILUER"