export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAILUER= "CREATE_ORDER_FAILUER"

export const GET_ORDER_BY_ID_REQUEST = "GET_ORDER_BY_ID_REQUEST"
export const GET_ORDER_BY_ID_SUCCESS = "GET_ORDER_BY_ID_SUCCESS"
export const GET_ORDER_BY_ID_FAILUER = "GET_ORDER_BY_ID_FAILUER"

export const GET_ORDER_HISTORY_REQUEST = "GET_ORDER_HISTORY_REQUEST"
export const GET_ORDER_HISTORY_SUCCESS = "GET_ORDER_HISTORY_SUCCESS"
export const GET_ORDER_HISTORY_FAILUER = "GET_ORDER_HISTORY_FAILUER"

export const COMFIRMED_ORDER_REQUEST = "COMFIRMED_ORDER_REQUEST"
export const COMFIRMED_ORDER_SUCCESS = "COMFIRMED_ORDER_SUCCESS"
export const COMFIRMED_ORDER_FAILUER= "COMFIRMED_ORDER_FAILUER"