export const COMRIRMED_ORDER_REQUEST = "COMRIRMED_ORDER_REQUEST"
export const COMFIREMD_ORDER_SUCCESS = "COMFIREMD_ORDER_SUCCESS"
export const COMFIREMD_ORDER_FAILUER = "COMFIREMD_ORDER_FAILUER"

export const PLACED_ORDER_REQUEST = "PLACE_ORDER_REQUEST"
export const PLACED_ORDER_SUCCESS = "PLACED_ORDER_SUCCESS"
export const PLACED_ORDER_FAILUER = "PLACED_ORDER_FAILUER"

export const DELIVERED_ORDER_REQUEST = "DELIVERED_ORDER_REQUEST"
export const DELIVERED_ORDER_SUCCESS = "DELIVERED_ORDER_SUCCESS"
export const DELIVERED_ORDER_FAILUER = "DELIVERED_ORDER_FAILUER"

export const CANCELED_ORDER_REQUEST = "CANCELED_ORDER_REQUEST"
export const CANCELED_ORDER_SUCCESS = "CANCELED_ORDER_SUCCESS"
export const CANCELED_ORDER_FAILUER = "CANCELED_ORDER_FAILUER"

export const DELETED_ORDER_REQUEST = "DELETED_ORDER_REQUEST"
export const DELETED_ORDER_SUCCESS = "DELETED_ORDER_SUCCESS"
export const DELETED_ORDER_FAILUER = "DELETED_ORDER_FAILUER"

export const SHIPED_ORDER_REQUEST = "SHIPED_ORDER_REQUEST"
export const SHIPED_ORDER_SUCCESS = "SHIPED_ORDER_SUCCESS"
export const SHIPED_ORDER_FAILUER = "SHIPED_ORDER_FAILUER"

export const ADMIN_GET_ORDERS_REQUEST = "ADMIN_GET_ORDERS_REQUEST"
export const ADMIN_GET_ORDERS_SUCCESS = "ADMIN_GET_ORDERS_SUCCESS"
export const ADMIN_GET_ORDERS_FAILUAR = "ADMIN_GET_ORDERS_FAILUAR"