export const FIND_PRODUCT_BY_ID_REQUEST = "FIND_PRODUCT_BY_ID"
export const FIND_PRODUCT_BY_ID_SUCCESS = "FIND_PRODUCT_BY_ID_SUCCESS"
export const FIND_PRODUCT_BY_ID_FAILUER = "FIND_PRODUCT_BY_ID_FAILUER"


export const FIND_PRODUCTS_REQUEST = "FIND_PRODUCT_REQUEST"
export const FIND_PRODUCTS_SUCCESS = "FIND_PRODUCTS_SUCCESS"
export const FIND_PRODUCTS_FAILUER = "FIND_PRODUCTS_FAILUER"

export const FIND_PRODUCTS_BY_CATEGORY_REQUEST = "FIND_PRODUCTS_BY_CATEGORY_REQUEST"
export const FIND_PRODUCTS_BY_CATEGORY_SUCCESS = "FIND_PRODUCTS_BY_CATEGORY_SUCCESS"
export const FIND_PRODUCTS__BY_CATEGORY_FAILUER = "FIND_PRODUCTS__BY_CATEGORY_FAILUER"

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILUAR = "DELETE_PRODUCT_FAILUAR"

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_FAILUAR = "CREATE_PRODUCT_FAILUAR"

