export const FIND_PRODUCT_BY_ID_REQUEST = "FIND_PRODUCT_BY_ID"
export const FIND_PRODUCT_BY_ID_SUCCESS = "FIND_PRODUCT_BY_ID_SUCCESS"
export const FIND_PRODUCT_BY_ID_FAILUER = "FIND_PRODUCT_BY_ID_FAILUER"


export const FIND_PRODUCTS_REQUEST = "FIND_PRODUCT_REQUEST"
export const FIND_PRODUCTS_SUCCESS = "FIND_PRODUCTS_SUCCESS"
export const FIND_PRODUCTS_FAILUER = "FIND_PRODUCTS_FAILUER"

